# Generated by Django 5.1.2 on 2024-10-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apaterno', models.CharField(max_length=50, verbose_name='Apaterno')),
                ('amaterno', models.CharField(max_length=50, verbose_name='Amaterno')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('fecha_naci', models.DateField(verbose_name='fecha_nacimiento')),
                ('fecha_falle', models.DateField(blank=True, null=True, verbose_name='fallecimiento')),
                ('fecha_ingre', models.DateField(blank=True, null=True, verbose_name='ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=400, verbose_name='comentario')),
                ('Alumno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsecundaria.alumno')),
            ],
        ),
    ]
